version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - './:/var/www/html/app'
    working_dir: /var/www/html/app
    ports:
      - '5111:5111'
      - '3555:3555'
